/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.checker;

/**
 *
 * @author MISHAN
 */
public class Id extends javax.swing.JFrame {

    /**
     * Creates new form Id
     */
    public Id() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        Enter = new javax.swing.JButton();
        txt_birthYear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_birthMonth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Gender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Date = new javax.swing.JTextField();
        txt_Error = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Checker"));

        jLabel1.setText("Enter ID");

        Enter.setText("ENTER");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        jLabel2.setText("Birth Year");

        jLabel3.setText("Birth Month");

        jLabel4.setText("Gender");

        jLabel5.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_birthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(txt_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Error)
                    .addComponent(txt_birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(Enter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_birthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_birthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txt_Error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        long id = Long.parseLong(txt_ID.getText());
        String s =String.valueOf(id);
        int length = s.length();
        
        if(length == 9) {
            
            String Year = s.substring(0,2);
//          System.out.println(s);
//          System.out.println(Year);
            String Month = s.substring(2,5);
        
            txt_birthYear.setText("19"+Year);
        
        
            String gender_num = s.substring(2,3);
            int Gender = Integer.parseInt(gender_num.trim());
            int i = 0;
            if(1<=Gender && Gender<=3) {
                txt_Gender.setText("Male");
                i = Integer.parseInt(Month.trim());
            }
            else if(5<=Gender && Gender<=8) {
                txt_Gender.setText("Female");
                i = Integer.parseInt(Month.trim());
                i = i-500;
            }
    
//            System.out.println(gender_num);
            String Date = "";

            if(i<=31) {
                txt_birthMonth.setText("January");
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(31<i && i<=60) {
                txt_birthMonth.setText("February");
                i=i-31;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(60<i && i<=91) {
                txt_birthMonth.setText("March");
                i=i-60;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(91<i && i<=121) {
                txt_birthMonth.setText("April");
                i=i-91;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(121<i && i<=152) {
                txt_birthMonth.setText("May");
                i=i-121;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(152<i && i<=182) {
                txt_birthMonth.setText("June");
                i=i-152;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(182<i && i<=213) {
                txt_birthMonth.setText("July");
                i=i-182;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(213<i && i<=244) {
                txt_birthMonth.setText("Auguest");
                i=i-213;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(244<i && i<=274) {
                txt_birthMonth.setText("September");
                i=i-244;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(274<i && i<=305) {
                txt_birthMonth.setText("Octomber");
                i=i-274;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(305<i && i<=335) {
                txt_birthMonth.setText("November");
                i=i-305;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(335<i && i<=366) {
                txt_birthMonth.setText("December");
                i=i-335;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }   
        }
        
        else if(length == 12){
            String Year = s.substring(0,4);
//          System.out.println(s);
//          System.out.println(Year);
            String Month = s.substring(4,7);
        
            txt_birthYear.setText(Year);
        
        
            String gender_num = s.substring(4,5);
            int Gender = Integer.parseInt(gender_num.trim());
            int i = 0;
            if(1<=Gender && Gender<=3) {
                txt_Gender.setText("Male");
                i = Integer.parseInt(Month.trim());
            }
            else if(5<=Gender && Gender<=8) {
                txt_Gender.setText("Female");
                i = Integer.parseInt(Month.trim());
                i = i-500;
            }
    
//            System.out.println(gender_num);
            String Date = "";

            if(i<=31) {
                txt_birthMonth.setText("January");
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(31<i && i<=60) {
                txt_birthMonth.setText("February");
                i=i-31;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(60<i && i<=91) {
                txt_birthMonth.setText("March");
                i=i-60;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(91<i && i<=121) {
                txt_birthMonth.setText("April");
                i=i-91;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(121<i && i<=152) {
                txt_birthMonth.setText("May");
                i=i-121;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(152<i && i<=182) {
                txt_birthMonth.setText("June");
                i=i-152;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(182<i && i<=213) {
                txt_birthMonth.setText("July");
                i=i-182;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(213<i && i<=244) {
                txt_birthMonth.setText("Auguest");
                i=i-213;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(244<i && i<=274) {
                txt_birthMonth.setText("September");
                i=i-244;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(274<i && i<=305) {
                txt_birthMonth.setText("Octomber");
                i=i-274;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(305<i && i<=335) {
                txt_birthMonth.setText("November");
                i=i-305;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
            else if(335<i && i<=366) {
                txt_birthMonth.setText("December");
                i=i-335;
                Date = Integer.toString(i);
                txt_Date.setText(Date);
            }
        }
        
        else{
            txt_Error.setText("Invalied ID Number");
        }
       
       
    }//GEN-LAST:event_EnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Id().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Error;
    private javax.swing.JTextField txt_Gender;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_birthMonth;
    private javax.swing.JTextField txt_birthYear;
    // End of variables declaration//GEN-END:variables
}
